#!/bin/bash
# This script sets up a machine with my preferred tools. It is aimed for either
# an Ubuntu or Mac machine. Obviously, it is heavily inspired by ubootstrap
# by rdegges which can be found here:
# https://github.com/rdegges/ubootstrap/blob/master/bootstrap.sh

platform=`uname`
if [[ "$platform" == 'Linux' ]]; then
  bash linux/install_packages
elif [[ "$platform" == 'Darwin' ]]; then
  bash osx/install_packages
fi

# Add dotfiles repository.
git clone https://github.com/majjoha/dotfiles.git $HOME/.env

# Install oh-my-zsh.
git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

# Change default shell from bash to zsh.
chsh -s /bin/zsh

# Install RVM and get the latest stable Ruby release.
curl -L https://get.rvm.io | bash -s stable --ruby

# Source RVM.
source $HOME/.rvm/scripts/rvm

# Symlink entire dotfiles repository.
cd $HOME && sudo bash $HOME/machine/bin/symlinktree $HOME/.env

# Source .zshrc.
source $HOME/.zshrc
